### ISSUE TITLE
eslint config "airbnb/hooks" not valid with eslint version:8.33.0

### ISSUE THREAD

**Issue by BrainEno** [electron-react-boilerplate/eslint-config-erb#139]
got this error after upgrade eslint to 8.33.0,please check if there's error in index.js
```
 'airbnb/hooks',
    ^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at module.exports [as default] (D:\workspace\electron-react-boilerplate\node_modules\import-fresh\index.js:32:59)
    at loadJSConfigFile (D:\workspace\electron-react-boilerplate\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2562:47)
    at loadConfigFile (D:\workspace\electron-react-boilerplate\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2646:20)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by amilajack** [comment]
unable to repro this on latest semver (eslint-config-erb@4.0.5). please comment if this is still an issue and I'll reopen
